# Generated by Django 2.1.5 on 2019-04-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
